only-fig-png: 
	realesrgan-ncnn-vulkan.exe -i input.png -o output.png

only-fig-jpg: 
	realesrgan-ncnn-vulkan.exe -i input.jpg -o output.jpg

folder-fig-png: 
	realesrgan-ncnn-vulkan.exe -i input -o output -n realesr-animevideov3 -s 2 -f png

folder-fig-jpg: 
	realesrgan-ncnn-vulkan.exe -i input -o output -n realesr-animevideov3 -s 2 -f jpg

#video